wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/models_CORA.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1642585145
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 2
      - 13
      - 16
      4: 3.7.11
      5: 0.12.9
      8:
      - 3
      - 5
dropout:
  desc: null
  value: Dropout(p=0.5, inplace=False)
epochs:
  desc: null
  value: 200
num_hidden:
  desc: null
  value: 16
