wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.9
    code_path: code/models_CORA.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1642628193
    t:
      1:
      - 1
      - 5
      3:
      - 13
      - 16
      4: 3.7.11
      5: 0.12.9
      8:
      - 3
      - 5
activation:
  desc: null
  value: ELU
dropout:
  desc: null
  value: 0.6
learning_rate:
  desc: null
  value: 0.0005
num_epochs:
  desc: null
  value: 1000
num_heads:
  desc: null
  value:
  - 8
  - 1
num_hidden:
  desc: null
  value: 8
optimizer:
  desc: null
  value: Adam
weight_decay:
  desc: null
  value: 0.005
